### ISSUE TITLE
Example of usage HarpNumericTable on C++ side

### ISSUE THREAD

**Issue by rlnx** [francktcheng/daal#3]
@francktcheng, please show how you are going to use `HarpNumericTable` on C++ side (maybe pseudo code). It will be helpful to better understand use cases.

**Comment by rlnx** [comment]
May be you've already used  `HarpNumericTable ` within algorithmic kernel, but I can't find.

**Comment by francktcheng** [comment]
@RuslanIsrafilov, in the current HarpNumericTable.h, we have only the interface of all the operations (the implementation is at java_harp_numeric_table.sh, which is invoked by HarpNumericTableImpl.java. ( e.g., in the cases of MF-SGD, and Subgraph). I am considering to have the equal implementation at the C++ side (e.g., a HarpHomogenNumericTable.h extended from HarpNumericTable ).

**Comment by rlnx** [comment]
You have implemented MF-SGD/Subgraph inside this fork in C++ and call implementation of that algorithm from HARP side, is my understanding right? Where can I find the HARP code of  MF-SGD/Subgraph which calls DAAL?

**Comment by francktcheng** [comment]
@RuslanIsrafilov, yes the c++ codes are invoked by Harp-DAAL mfsgd, which is at 
https://github.com/francktcheng/harp/blob/develop/experimental/src/main/java/edu/iu/daal_sgd/SGDDaalCollectiveMapper.java
